import Head from 'next/head'
import Layout from '@/components/Layout/Layout'
import { useAccount, useSigner } from 'wagmi'
import { Text, useToast, Image, Flex, Center } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'
import { useRouter } from 'next/router'

export default function Home() {

  const { address, isConnected } = useAccount()
  const { data: signer } = useSigner()
  const toast = useToast()
  const router = useRouter()

  
  
  return (
    <>
      <Head>
        <title>DApp4Movie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {isConnected ? (
          <Flex>
          <Text fontSize='5xl'> DApp4Movies </Text>
          <Image
            src="/DAppFMbis.png"
            width='40'
            height='40'
          />
          </Flex>
        ) : (
          <Alert status='warning' width="50%">
            <AlertIcon />
            Please, connect your Wallet!
          </Alert>
        )}
      </Layout>
    </>
  )
}