import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Layout from '@/components/Layout/Layout'
import { useAccount, useProvider, useSigner } from 'wagmi'
import { Text, Flex, Button, Input, useToast } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'
import { useState } from 'react'
import { ethers } from 'ethers'
import { contractAddress, abi } from '../public/abis/marketPlace'


export default function Market() {

    const { address, isConnected } = useAccount()
    const provider = useProvider()
    const { data: signer } = useSigner()
    const toast = useToast()
    const router = useRouter()
  
    const setTheNumber = async() => {
      try {
          const contract = new ethers.Contract(contractAddress, abi, signer)
          let transaction = await contract.setNumber(number)
          await transaction.wait()
          router.push('/getNumber')
          toast({
              title: 'Congratulations',
              description: "the number has been changed!",
              status: 'success',
              duration: 4000,
              isClosable: true,
          })
      }
      catch(e) {
          toast({
              title: 'Error',
              description: "An error occured.",
              status: 'error',
              duration: 4000,
              isClosable: true,
          })
          console.log(e)
      }
      
    }
    
    return (
      <>
        <Head>
          <title>DApp4Movies : MarketPlace</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          {isConnected ? (
            <Flex alignItems="center">
              <h1>MarketPlace</h1>
              {/* <Button colorScheme='blue' onClick={() => getTheNumber()}>Get the number</Button>
              {number ? (
                  <Text ml="1rem">{number}</Text> 
              ) : (
                  <Text ml="1rem">Please, click on this button to get the number.</Text>
              )}  */}
            </Flex>
          ) : (
            <Alert status='warning' width="50%">
              <AlertIcon />
              Please, connect your Wallet!
            </Alert>
          )}
        </Layout>
      </>
    )
  }
  